import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./{components}/Navbar";
import Footer from "./{components}/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${inter.className} bg-white gap-0 max-w-[100rem] py-2 lg:py-4 text-black relative mx-auto flex flex-col items-center`}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
